version: '3'
services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/cmd/web
    ports:
      - 4000:4000
    environment:
      - GOPATH=/go
      - GO111MODULE=on
      - GOMOD=/app/go.mod
